version: '3.4'

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
    Todo.Api:
        image: ${DOCKER_REGISTRY-}todoapi
        build:
            context: .
            dockerfile: Todo.API/Dockerfile
    Todo.App:
        image: ${DOCKER_REGISTRY-}todoapp
        build:
            context: .
            dockerfile: Todo.App/Dockerfile