version: '3.4'

services:
    mssql:
        container_name: mssql
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
          - SA_PASSWORD=Pass@word
          - ACCEPT_EULA=Y
        restart: unless-stopped 
        ports:
          - "1433:1433"
    Todo.Api:
        container_name: Api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - "ConnectionStrings:TodoConnectionString=Server=mssql,1433;Database=TodoDB;User Id=sa;Password=Pass@word;TrustServerCertificate=True;"
        depends_on:
            - mssql
        ports:
            - "5102:80"
    Todo.App:
        container_name: App
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - APIConfiguration:Version=v1
            - APIConfiguration:Url=http://host.docker.internal:5102/
        depends_on:
            - Todo.Api
        ports:
            - "5103:80"