version: '3.4'

services:
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql
        hostname: mssql
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
          - SA_PASSWORD=Pass@word
          - ACCEPT_EULA=Y
        restart: unless-stopped 
        ports:
          - "5432:1433"
    Todo.Api:
        image: ${DOCKER_REGISTRY-}todoapi
        container_name: Api
        hostname: Api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        build:
            context: .
            dockerfile: Todo.API/Dockerfile
        depends_on:
            - sqldata
        ports:
            - "5102:80"
    Todo.App:
        image: ${DOCKER_REGISTRY-}todoapp
        container_name: App
        hostname: App
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        build:
            context: .
            dockerfile: Todo.App/Dockerfile
        depends_on:
            - Todo.Api
        ports:
            - "5103:80"